### ISSUE TITLE
Generate a client and informer for Metacontroller APIs

### ISSUE THREAD

**Issue by enisoc** [GoogleCloudPlatform/kube-metacontroller#3]
We need to use the dynamic client for the objects that Lambda Controllers manage, since we allow them to manage arbitrary objects.

However, there are advantages to using a generated client to access objects that represent the Metacontroller APIs themselves (e.g. `CompositeController`).

[This blog](https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/) may be useful.

**Comment by antoineco** [comment]
@enisoc I could give this a shot, ping me if you need a hand. I'm using kubernetes [code generators](https://github.com/kubernetes/code-generator) myself to write some custom controllers currently, so I could directly apply the know-how.

**Comment by enisoc** [comment]
@antoineco That would be great! Please feel free to take a shot. :)
